import { User } from "./types/user";

export const users: User[] = [
  {
    id: 0,
    name: "احمد اسامة احمد",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 1,
    name: "ارام ماهر محمد",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 2,
    name: "اوس حارث إبراهيم",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 3,
    name: "ذوالفقار حسن عبد الحسين",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 4,
    name: "عباس احمد عباس",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 5,
    name: "عبدالله حسين مطشر",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 6,
    name: "عبدالله خالد غريب",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 7,
    name: "عبدالله طلال فاضل",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 8,
    name: "عبدالله محمد إسماعيل",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 9,
    name: "عبدالله وائل ياسين",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 10,
    name: "عبدالعزيز عبدالمناف حميد",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 11,
    name: "عبدالكريم يوسف عبدالرحيم",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 12,
    name: "علي حسن محمد",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 13,
    name: "محمد سمير عبد محسن",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 14,
    name: "مصطفى اسماعيل حسين",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 15,
    name: "مصطفى خالد تركي",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 16,
    name: "مصطفى صلاح كاظم",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 17,
    name: "اساور اياس كمال",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 18,
    name: "ايات نصير عبدالجبار",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 19,
    name: "اية احمد شكر",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 20,
    name: "ايثار سعد تركي",
    gender: "MALE",
    monthlyEvents: [],
  },
  {
    id: 21,
    name: "ايمان عبد القادر خضير",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 22,
    name: "ايمان مالك ناجي",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 23,
    name: "إحسان حامد محمد",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 24,
    name: "أسماء جواد هاشم",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 25,
    name: "تبارك علي كنعان",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 26,
    name: "تبارك وليد شنين",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 27,
    name: "دانية ياسر عبدالوهاب",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 28,
    name: "دانيه جليل حسين",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 29,
    name: "دانيه وليد عبدالكريم",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 30,
    name: "دينا محسن حسن",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 31,
    name: "رسل كريم محمد",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 32,
    name: "رغد صفاء عبدالكريم",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 33,
    name: "ريام اياد طه",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 34,
    name: "زهراء هلال حسين",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 35,
    name: "زهراء يوسف العبد",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 36,
    name: "زينب الحوراء كريم فريح",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 37,
    name: "زينب محمد علي",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 38,
    name: "سارة كريم محمد",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 39,
    name: "سدن حكمت عبدالرحيم",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 40,
    name: "سرى علي حسين",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 41,
    name: "سلا خالد كامل",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 42,
    name: "شوق عماد عبدالمهدي",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 43,
    name: "عذراء علاء مهدي",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 44,
    name: "غدير حاتم حسن",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 45,
    name: "غفران مأمون جاسم",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 46,
    name: "فوز مزاحم فتاح",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 47,
    name: "مروة خالد ثابت",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 48,
    name: "مريم سعد كريم",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 49,
    name: "مريم ضياء احمد",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 50,
    name: "مريم ماجد محمد",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 51,
    name: "ملاك سعد كريم",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 52,
    name: "مها عبدالكريم قاسم",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 53,
    name: "مودة عارف حمادي",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 54,
    name: "ميس سفيان احمد",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 55,
    name: "مينا عماد كاظم",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 56,
    name: "مينا محمد عبد الرضا",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 57,
    name: "نادين علاء عبدالكريم",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 58,
    name: "نبأ حيدر حسن",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 59,
    name: "نور رائد محمد",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 60,
    name: "نور رمزي محمد",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 61,
    name: "هالة وليد عادل",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 62,
    name: "هبة علي هلال",
    gender: "FEMALE",
    monthlyEvents: [],
  },
  {
    id: 63,
    name: "يقين سلمان شمران",
    gender: "MALE",
    monthlyEvents: [],
  },
];
